dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.0.1
  audio_session: ^0.1.21
  just_audio: ^0.9.35
  record: ^5.0.1
  path_provider: ^2.1.2
  path: ^1.8.3
  intl: ^0.18.1
  flutter_audio_waveforms: ^4.4.0
